<html>
<head>
	<base href="http://localhost/apprentice_cms/application/modules/news/views/scripts/article/">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />	
	<?php echo $this->headTitle('Add new article') ?>	
	<?php echo $this->headLink()->appendStylesheet("editor.css") ?>
	<?php echo $this->headStyle()?>
	<?php echo $this->headScript()->appendFile("editor.js") ?>
	<h2><center><a href="<?php echo $this->url(array('article_id' => "$this->article_id"), 'news_article_view'); ?>"><?php echo $this->message ?></a></center></h2>
</head>

<body>
<form action="" method="post" name="addArticleForm" id="addArticleForm" enctype="multipart/form-data">
	<div>
		<label>Main title: </label>
		<input type="text" name="title" id="title" style="width: 440px" />
	</div>
	
	<hr />
	
	<div>
		<label>Slug: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
		<input type="text" name="slug" id="slug" style="width: 440px" />
	</div>
	
	<hr />
	
	<div>
		<label>Description:</label>
		<span id="editorDescription">Waiting for loading editor...</span>
		<script language="javascript">
			ed = new Editor("ed", "d", "description", "editorDescription", 440, 200);
			ed.render();
		</script>
	</div>
	
	<hr />
	
	<div>
		<label>Content:</label>
		<span id="editorContent">Waiting for loading editor...</span>
		<script language="javascript">
			ec = new Editor("ec", "c", "content", "editorContent", 440, 600);
			ec.render();
		</script>
	</div>
	
	<hr />
	
	<div>
		<label>Author: &nbsp;&nbsp;&nbsp;</label>
		<input type="text" name="author" id="author" style="width: 440px" />
	</div>
	
	<hr />
	
	<div>
		<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
		<input type="checkbox" name="allowComment" id="allowComment" value="1" /> Allow user to comment article
	</div>
	
	<hr />
	
	<div>
		<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
		<input type="checkbox" name="hotArticle" id="hotArticle" value="1" /> Hot article
	</div>
	
	<hr />
	
	<div>
		<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
		<input type="submit" name="save" value="Save" onclick="getData('description', 'd'); getData('content', 'c');" />
	</div>
</form>

</body>
</html>