<?php echo $this->doctype(); ?>
<html>
<head>
	<?php echo $this->headLink()->appendStylesheet('/Apprentice_CMS/public/css/StyleSheet.css'); ?>
    <link type="text/css" rel="Stylesheet" href="StyleSheet.css" />
    
    <link type="text/css" href="/Apprentice_CMS/public/css/jquery-ui-1.8.16.custom.css" rel="stylesheet" />    
	<script type="text/javascript" src="/Apprentice_CMS/public/js/jquery-1.6.2.min.js"></script>
	<script type="text/javascript" src="/Apprentice_CMS/public/js/jquery-ui-1.8.16.custom.min.js"></script>
	<script type="text/javascript">

			$(function(){
				// Dialog			

				$('#dialog-title').dialog({

					autoOpen: false,

					width: 600				

				});	

				$('#dialog-description').dialog({

					autoOpen: false,

					width: 600				

				});		

				$('#dialog-author').dialog({

					autoOpen: false,

					width: 600				

				});			

				// Dialog Link

				$('#dialog_link-title').click(function(){

					$('#dialog-title').dialog('open');

					return false;

				});		

				$('#dialog_link-description').click(function(){

					$('#dialog-description').dialog('open');

					return false;

				});		

				$('#dialog_link-author').click(function(){

					$('#dialog-author').dialog('open');

					return false;

				});						

				//hover states on the static widgets

				$('#dialog_link-title,#dialog_link-description,#dialog_link-author').hover(

					function() { $(this).addClass('ui-state-hover'); }, 

					function() { $(this).removeClass('ui-state-hover'); }

				);

			});

		</script>
	
</head>
<body>

	
	<div id="dialog-title" title="Title">
			<?php echo $this->article_id;?>
			<?php echo $this->action('edittitle', 'article','news');?>
			
	</div>	
	
	<div id="dialog-description" title="Description">
			<?php echo $this->action('editdescription', 'article','news');?>
	</div>	
	
	<div id="dialog-author" title="Author">
			<?php echo $this->action('editauthor', 'article','news');?>
	</div>	
	
    <div id="main">  
    	<h4>Chỉnh sửa bài viết</h4>      
        <div class="block">
        
            <h3>Title</h3>
            <div id="titles">
                <p id="dialog_link-title" ><?php echo $this->newsTitle?></p>
            </div>
            
            <div class="control">
                <a href="#" title="Edit"><img src="/Apprentice_CMS/public/images/icon/Edit.png" /> </a>
            </div>
            <div class="clear"></div>
        </div>
        
        <div class="block">
            <h3>Description</h3>
            <div id="description">
                <p id="dialog_link-description" ><?php echo $this->newsDescription?></p>
            </div>
            
            <div class="control">
                <a href="#" title="Edit"><img src="/Apprentice_CMS/public/images/icon/Edit.png" /> </a>
            </div>
            <div class="clear"></div>
        </div>
        
        <div class="block">
            <h3>Order news</h3>
            <div id="order">

            </div>
            
            <div class="control">
                <a href="#" title="Edit"><img src="/Apprentice_CMS/public/images/icon/Edit.png" /> </a>
            </div>
            <div class="clear"></div>
        </div>
        
        <?php         	
        	$temp=new SimpleXMLElement($this->newsContent);        		
        	foreach ($temp->children() as $t){
        		$i=0;
        		foreach($t->children() as $s){        			
        			if($s["class"]=='img'){
        				$i++;
        				break;
        			}
        		}
        		if($i==0){
        			$dom=dom_import_simplexml($t);
        			$child=$dom->ownerDocument->createElement("h3","Block Content");
        			$control=$dom->ownerDocument->createElement("div");
        			$control->setAttribute("class", "control");
        			
        			$edit=$control->ownerDocument->createElement("a");
        			$edit->setAttribute("href", "#");
        			$edit->setAttribute("title", "Edit");
        			$imgEdit=$edit->ownerDocument->createElement("img");
        			$imgEdit->setAttribute("src", "/Apprentice_CMS/public/images/icon/Edit.png");
        			$edit->appendChild($imgEdit);
        			$control->appendChild($edit);
        			
        			$moveup=$control->ownerDocument->createElement("a");
        			$moveup->setAttribute("href", "#");
        			$moveup->setAttribute("title", "Move Up");
        			$imgMoveup=$moveup->ownerDocument->createElement("img");
        			$imgMoveup->setAttribute("src", "/Apprentice_CMS/public/images/icon/Up.png");
        			$moveup->appendChild($imgMoveup);
        			$control->appendChild($moveup);
        			
        			$movedown=$control->ownerDocument->createElement("a");
        			$movedown->setAttribute("href", "#");
        			$movedown->setAttribute("title", "Move Down");
        			$imgMovedown=$movedown->ownerDocument->createElement("img");
        			$imgMovedown->setAttribute("src", "/Apprentice_CMS/public/images/icon/Down.png");
        			$movedown->appendChild($imgMovedown);
        			$control->appendChild($movedown);
        			
        			$delete=$control->ownerDocument->createElement("a");
        			$delete->setAttribute("href", "#");
        			$delete->setAttribute("title", "Delete Block");
        			$imgDelete=$delete->ownerDocument->createElement("img");
        			$imgDelete->setAttribute("src", "/Apprentice_CMS/public/images/icon/Delete.png");
        			$delete->appendChild($imgDelete);
        			$control->appendChild($delete);
        			
        			$clear=$dom->ownerDocument->createElement("div","");
        			$clear->setAttribute("class", "clear");
        			//$control->appendChild($clear);
        			
        			$dom->insertBefore($child,$dom->firstChild);
        			$dom->appendChild($control);
        			$dom->appendChild($clear);       			
        			echo $t->asXML();
        			
        			$te=new SimpleXMLElement("<div class='panel'>
            		<a href='#' title='New block content'><img src='/Apprentice_CMS/public/images/icon/New-document.png' /> </a>
            		<a href='#' title='New image'><img src='/Apprentice_CMS/public/images/icon/New-image.png' /> </a>
            		<a href='#' title='New table'><img src='/Apprentice_CMS/public/images/icon/New-table.png' /> </a>
        			</div>");
        			echo $te->asXML();
        		}
        		
        		else{
        			$dom=dom_import_simplexml($t);
        			$child=$dom->ownerDocument->createElement("h3","Block Image");
        			$control=$dom->ownerDocument->createElement("div");
        			$control->setAttribute("class", "control");
        			
        			$edit=$control->ownerDocument->createElement("a");
        			$edit->setAttribute("href", "#");
        			$edit->setAttribute("title", "Edit");
        			$imgEdit=$edit->ownerDocument->createElement("img");
        			$imgEdit->setAttribute("src", "/Apprentice_CMS/public/images/icon/Edit.png");
        			$edit->appendChild($imgEdit);
        			$control->appendChild($edit);
        			
        			$moveup=$control->ownerDocument->createElement("a");
        			$moveup->setAttribute("href", "#");
        			$moveup->setAttribute("title", "Move Up");
        			$imgMoveup=$moveup->ownerDocument->createElement("img");
        			$imgMoveup->setAttribute("src", "/Apprentice_CMS/public/images/icon/Up.png");
        			$moveup->appendChild($imgMoveup);
        			$control->appendChild($moveup);
        			
        			$movedown=$control->ownerDocument->createElement("a");
        			$movedown->setAttribute("href", "#");
        			$movedown->setAttribute("title", "Move Down");
        			$imgMovedown=$movedown->ownerDocument->createElement("img");
        			$imgMovedown->setAttribute("src", "/Apprentice_CMS/public/images/icon/Down.png");
        			$movedown->appendChild($imgMovedown);
        			$control->appendChild($movedown);
        			
        			$delete=$control->ownerDocument->createElement("a");
        			$delete->setAttribute("href", "#");
        			$delete->setAttribute("title", "Delete Block");
        			$imgDelete=$delete->ownerDocument->createElement("img");
        			$imgDelete->setAttribute("src", "/Apprentice_CMS/public/images/icon/Delete.png");
        			$delete->appendChild($imgDelete);
        			$control->appendChild($delete);
        			
        			$clear=$dom->ownerDocument->createElement("div","");
        			$clear->setAttribute("class", "clear");
        			//$control->appendChild($clear);
        			
        			$dom->insertBefore($child,$dom->firstChild);
        			$dom->appendChild($control);
        			$dom->appendChild($clear);       			
        			echo $t->asXML();
        			
        			$te=new SimpleXMLElement("<div class='panel'>
            		<a href='#' title='New block content'><img src='/Apprentice_CMS/public/images/icon/New-document.png' /> </a>
            		<a href='#' title='New image'><img src='/Apprentice_CMS/public/images/icon/New-image.png' /> </a>
            		<a href='#' title='New table'><img src='/Apprentice_CMS/public/images/icon/New-table.png' /> </a>
        			</div>");
        			echo $te->asXML(); 
        		}
        				
        	}
        ?>

        <div class="block">
            <h3>Author</h3>
            <div id="author">
                <p id="dialog_link-author" ><?php echo $this->newsAuthor?></p>
            </div>
            
            <div class="control">
                <a href="#" title="Edit"><img src="/Apprentice_CMS/public/images/icon/Edit.png" /> </a>
            </div>
            <div class="clear"></div>
        </div>
        <div class="button">
        	<a href="#" title="Save">
        		<img src="/Apprentice_CMS/public/images/icon/Save32.png" />
        	</a>
        </div>	
    </div>
</body>
</html>
