<html>
<head>
	<base href="http://localhost/apprentice_cms/application/modules/news/views/scripts/article/">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />	
	<?php echo $this->headTitle('View the article') ?>	
	<?php echo $this->headLink()->appendStylesheet("editor.css") ?>
	<?php echo $this->headStyle()?>
	<?php echo $this->headScript()->appendFile("editor.js") ?>
</head>
<body>
	<hr />
	<h2><?php echo $this->title ?></h2>
	<cite><?php echo $this->author . " - " . $this->created_date ?></cite>
	<hr />
	<?php echo $this->description ?>
	<hr />
	<?php echo $this->content ?>
	<hr />
	<?php
		if ($this->allowComment == 1)
			echo '<div>
					<label>Comment:</label>
					<span id="editorComment">Waiting for loading editor...</span>
					<script language="javascript">
						ec = new Editor("ec", "c", "description", "editorComment", 440, 200);
						ec.render();
					</script>
				  </div> <hr />'; 
	?>
</body>
</html>