<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
<div>
	<form action="" method="post" id="filteruser">
		<table>
			<tr>
				<td>UserName</td>
				<td><input type="text" name="tbxuser" /></td>
				<td>Email</td>
				<td><input type="text" name="tbxemail" /></td>
			</tr>
			<tr>
				<td>Groups</td>
				<td><select></select></td>
				<td>Action</td>
				<td><select name="cbxaction"><option value="" >---</option><option value="0" >Deactive</option><option value="1" >Active</option></select></td>
			</tr>
			<tr>
				<td><input type="submit" name="btnsubmit" value="Filter" /></td>
			</tr>
		</table>
	</form>
</div>
<hr />
<div>
	<table>
		
		<?php 
			if($this->data!=null){
				echo "<tr>";
				echo "<td>Username</td>";
				echo "<td>Email</td>";
				echo "<td>ID</td>";
				echo "</tr>";
				foreach($this->data as $item){
					echo "<tr>";
					echo "<td>".$item["user_name"]."<br />";
					echo "<a href='edit/id/".$item['user_id']."'>edit  </a>";
					echo "<a href='rule/id/".$item['user_id']."'>| role  </a>";
					if($item['user_name']!="admin"){
						if($item["is_active"]==0)
							echo "<a href='active/id/".$item['user_id']."'>| active  </a>";
						else 
							echo "<a href='deactive/id/".$item['user_id']."'>| deactive  </a>";
					}
					echo "</td>";
					echo "<td>".$item["email"]."</td>";
					echo "<td>".$item["user_id"]."</td>";
					echo "</tr>";
				}
			}else{
				echo "ko có user nào hết ";
			}
		?>
	</table>
</div>
</body>
</html>