<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />		
		<?php echo $this->headTitle('Login')?>
		<?php echo $this->headLink()->appendStylesheet("http://localhost:8080/Apprentice_CMS/public/css/login.css") ?>
		<?php echo $this->headStyle()?>
		<?php echo $this->headScript()?>
	</head>
	<body>
		<p>
		<?php 
			if ($this->auth) // successful authentication 
			{ 
    	?> 
    	You are already authenticated, 
    	<?php  echo Zend_Auth::getInstance()->getIdentity()->user_name ?>. 
    	</p> 
    	<p> 
     
    	<?php 
			} 
		else { 
    	if (isset($this->messages)) { 
        ?> 
        The following problems were encountered with your last login attempt: 
        </p> 
        <p> 
        <?php 
        foreach ($this->messages as $field => $messages) { 
        ?> 
            <b><?php echo $this->escape($field) ?></b> 
            <?php 
            foreach ($messages as $message) { 
                echo $this->escape($message) . "\n"; 
            } 
            ?> 
            </p> 
            <?php 
        	} 
    	}    
    	?> 
		<form action="#" method="post" id="login">
		<div id="head">
			<!--php khi khong dung Zend_auth 
			if($this->error!=null){
				echo "<ul>";
				foreach($this->error as $item){
					echo "<li>$item</li>";
				}
				echo "</ul>";
			}
			if($this->message!=NULL){
				echo "<ul>";
				foreach($this->message as $item){
					echo "<li>$item</li>";
				}
				echo "</ul>";
			}
			?>-->
		</div>
		<div id="content">
			<div class="content-left">
			</div>
			<div class="content-text">
				<div class="content-sub">
					<p id="user">
						<h6 class="username">User name:</h6>
						<input type="text" class="txtusername" name="txtuser" id="txtuser"/>
					</p>
				</div>
				<div class="content-sub">
					<p id="pass"> 
						<h6 class="password">Password:</h6>
						<input type="password" class="txtpassword" name="txtpass" id="txtpass"/>
					</p>
				</div>
				<div class="content-sub">
					<p id="forgot"><a href="">Forgot your password</a></p>
					<input type="submit" class="btn" value="Login"></input>
				</div>
				<div class="content-center">
				</div>
			</div>
			<div class="content-right">
			</div>
		</div>
		<div id="footer">
			<div id="head_footer">
				<div id="content_footer">
					<h6>Powered by Ap_CMS</h6>
				</div>
			</div>
		</div>
		</form>
		<?php 
} 
?> 
	</body>
</html>


