<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />		
		<?php echo $this->headTitle('Admin')?>
		<?php echo $this->headLink()->appendStylesheet("http://localhost/Apprentice_CMS/public/css/admin.css") ?>
		<?php echo $this->headStyle()?>
		<?php echo $this->headScript()?>
	</head>
	<body>
		<div id="container">
	    
	        <div id="header">
	            <h3>Administrator Menu</h3>
	        </div><!--header-->
	        
	        <div id="content">
	            <div id="myAccount"><a href="#"><img src="images/My Account.png"/></a></div>
	            <div id="systemLog"><a href="#"><img src="images/System Log.png"/></a></div>
	            <div id="roles"><a href="#"><img src="images/Roles.png"/></a></div>
	            <div id="advancedTool"><a href="<?php echo "http://localhost/Apprentice_CMS/public/admin/module/list"?>"><img src="images/Advanced Tool.png"/></a></div>
	            <div id="contentManager"><a href="#"><img src="images/Content Manager.png"/></a></div>
	            <div id="memberManager"><a href="#"><img src="images/Member Manager.png"/></a></div>
	            <div id="siteManager"><a href="#"><img src="images/Site Manager.png"/></a></div>
	        </div><!--content-->
	        
	        <div id="footer">
	            <div id="infor">
	                <ul>
	                    <li><a href="#">Home</a></li>
	                    <li><a href="#">Products</a></li>
	                    <li><a href="#">Download</a></li>
	                    <li><a href="#">Support</a></li>
	                    <li><a href="#">About Us</a></li>
	                    <li><a href="#">Contact</a></li>
	                    <li><a href="#">Privacy Policy</a></li>
	                </ul>
	            </div>
	        </div><!--footer-->
	    </div><!--container-->
	</body>
</html>