<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />		
		<?php echo $this->headTitle('Admin')?>
		<?php echo $this->headLink()->appendStylesheet(URL_CSS.'/admin.css')?>
		<?php echo $this->headStyle()?>
		<?php echo $this->headScript()?>
		
		<style type="text/css">
		   .container{
		    padding:0px;
		    margin: 0 auto;
		    max-width: 1260px;
		    min-width: 850px;
		
		    background:#205FAA;
		   }
		   .header{
		   	border-bottom: 5px blue solid;"
			}
		   .header li{
		    display: inline;
		   }
		   .header li a{
		    font-size: 20px;
		    background: #D83505;
		    text-decoration:none;
		    margin-left: 20px;
		    -moz-border-radius:5px;
		   }
		   .header li a:hover{
		    background:#B5B5B5;
		   }
		   .content{
		    width: auto;
		   }
		   .footer{
		    background:#151AC8;
		    text-align:right;
   			}
	</style>
	</head>
	<body>
		<div id="container">
	    
	        <div id="header">
	            <h3>Administrator Menu</h3>
	        </div><!--header-->
	        
	        <div id="content">
	        
	            <div id="myAccount"><a href="#"><img src="<?php echo URL_IMG?>/My Account.png"/></a></div>
	            <div id="systemLog"><a href="#"><img src="<?php echo URL_IMG?>/System Log.png"/></a></div>
	            <div id="roles"><a href="../admin/role/submit"><img src="<?php echo URL_IMG?>/Roles.png"/></a></div>
	            <div id="advancedTool"><a href="<?php echo "http://localhost/Apprentice_CMS/public/admin/module/list"?>"><img src="<?php echo URL_IMG?>/Advanced Tool.png"/></a></div>
	            <div id="contentManager"><a href="#"><img src="<?php echo URL_IMG?>/Content Manager.png"/></a></div>
	            <div id="memberManager"><a href="http://localhost/Apprentice_CMS/public/admin/privilege/list"><img src="<?php echo URL_IMG?>/Member Manager.png"/></a></div>
	            <div id="siteManager"><a href="<?php echo "http://localhost/Apprentice_CMS/public/admin/template/list"?>"><img src="<?php echo URL_IMG?>/Site Manager.png"/></a></div>
	        </div><!--content-->
	        
	        <div id="footer">
	            <div id="infor">
	                <ul>
	                    <li><a href="#">Home</a></li>
	                    <li><a href="#">Products</a></li>
	                    <li><a href="#">Download</a></li>
	                    <li><a href="#">Support</a></li>
	                    <li><a href="#">About Us</a></li>
	                    <li><a href="#">Contact</a></li>
	                    <li><a href="#">Privacy Policy</a></li>
	                </ul>
	            </div>
	        </div><!--footer-->
	    </div><!--container-->
	</body>
</html>