<?php echo $this->doctype(); ?>
<html>
<head>
   <?php echo $this->headMeta(); ?>
   <?php echo $this->headTitle(); ?>
   <?php echo $this->headLink(); ?>
</head>
<body style="width: 80%; margin-left: auto; margin-right: auto">
<h1>Test Template 1</h1>
        <div style="width: 100%; background-color: gray">
            <div style="width: 100%;background-color:teal">
                <a href="index">home</a><a style="margin-left: 10px" href="layout">Layout</a>
                <br><br>
            </div>

            <div style="width: 100%; margin-top: 50px">

                <?php echo $this->layout()->content ?>
                
            </div>    
        </div>

</body>
</html>