<?php echo $this->doctype(); ?>
<html>
<head>
   <?php echo $this->headMeta(); ?>
   <?php echo $this->headTitle(); ?>
   <?php echo $this->headLink()->appendStylesheet('../../../skin/testTemplate1/default/default.css'); ?>
 
</head>
<body>   
	<div class="container">
    	<div class="header">
            <h1>Apprentice_CMS_Template1</h1>
        	<ul>
            	<li><a href="http://localhost/Apprentice_CMS/public/admin">Admin</a></li>
                <li><a href="http://localhost/Apprentice_CMS/public/news/article/list">News</a></li>
                <li><a href="#">module</a></li>
            </ul>
        </div><!--header-->

        <div class="content">
			<div class="news" style="">
				<?php echo $this->layout()->content?>
			</div>
                
        </div><!--content-->  
            
        <div class="footer">
            <h4>Power By Apprectice_CMS</h4>
        </div> 
             
	</div><!--container-->
</body>
</html>