<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />		
		<?php echo $this->headTitle('Template')?>
		<?php echo $this->headLink()?>
		<?php echo $this->headStyle()?>
		<?php echo $this->headScript()?>
		<style type="text/css">
			@CHARSET "UTF-8";
			{
			margin:0;
			padding:0;
			}
			.container{
			width:960px;
			height:960px;
			border:black 1px solid;
			margin:10px auto;
			}
			
			.header{
			text-align:center;
			border:yellow 1px solid;
			background:#333;
			}
			.nav{
			border:blue 1px solid;	
			}
			.content{
			border:red 2px solid;
			height:790px;
			}
			.template{
			border:blue 1px solid;
			width:280px;
			float:left;
			margin:10px;
			margin-left:10px;
			}
			.template_infor{
			font-size:13px;
			}
			.template_img{
			width:120px;
			height:120px;
			border:1px solid black;
			}
			.skin:hover{
			background:#333;
			}
			
			.skin_text{
			float:left;
			}
			
		</style>
	</head>
	<body>
		<div class="container">
			<div class="header">
				<h1>Template</h1>
			</div>
			<div class="nav">
				<p>Dưới đây là danh sách các template. Bạn có thể chọn template và skin cho trang web.</p>
			</div>
			<div class="content">
				<?php foreach ($this->templates as $template){?>
					<div class="template">
						<div class="template_name">
							<h2><?php echo $template['name'];?></h2>
						</div>
						
						<div class="template_infor">
							<?php echo "Tác Giả: " . $template['author']; ?><br />
							<?php echo "Phiên Bản: " . $template['version']; ?>
						</div>
						
						<div class="template_img">
							<img src="images/paper.jpg">Hình ảnh Template: <?php echo $template['name'];?></img>
						</div>
						
						<p>Bạn có thể sử dụng một trong các skin sau:</p>
						
						<div class="skin">
							<div class="skin_text">Default Skin: </div>
							<div class="skin_action">
								<form action="#" method="get">
									<input type="button" value="Chọn" id="skin_btnChon"></input>
									<input type="button" value="Sửa" id="skin_btnSua"/>
								</form>
							</div>
						</div>
						
						<div class="template_action">
							<form action="../gui/<?php $this->dirname;?>" method="get">
								<input type="submit" value="Chọn Template" 
								onclick="<?php 
								$this->dirname=$template['name'];
								echo $this->dirname;?>"/>
							</form>
						</div>
						
					</div>
				<?php }?>	
			</div>
			
		</div>
	</body>
</html>


