<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?php echo $this->headLink()->appendStylesheet('../../../skin/admin/default/admin.css'); ?>
   	<?php echo $this->headScript()->appendFile('../../../js/admin/stmenu.js')
								   ->appendFile('../../../js/admin/stcode.js')
								   ->appendFile('../../../js/admin/steffie.js')
								   ->appendFile('../../../js/admin/steffslip.js')
								   ->appendFile('../../../js/admin/steffrect.js');?>
   
</head>
<body>   
	
</body>
</html>