<?php echo $this->doctype(); ?>
<html>
	<head>
		<base href="<?php echo $this->baseUrl(); ?>" />
		<?php 
			
			echo $this->headTitle();
			$this->headLink()->appendStylesheet($this->url."skin/admin/default/style.css");			
		?>
		<?= $this->headLink() ?>
		<?= $this->headScript() ?> 
		
	</head>
<body>
		<div id="pageWrapper">
			<div id="header">
				<h1>Zend Framework CMS</h1>
			</div>
			<div id="nav">
				<?php echo $this->layout()->nav;?>
			</div>
			<div id="sidebar">
				<div id="subNav">
					<?php echo $this->layout()->subNav?>
					<h1>Apprentice_CMS</h1>
		        	<ul>
		            	<li><a href="http://localhost/Apprentice_CMS/public/admin">Admin</a></li>
		                <li><a href="http://localhost/Apprentice_CMS/public/news/article/list">News</a></li>
		                <li><a href="#">module</a></li>
		            </ul>
				</div>
				<div id="adminMenu">
					<?php echo $this->layout()->adminMenu?>
				</div>
				<div id="userForm">
					<?php echo $this->layout()->userForm?>
				</div>
			</div>
			<div id="main">
				<?php echo $this->layout()->content;
				?>
			</div>
			<div id="footer">
				<p>Powered by Zend Framework</p>
			</div>
		</div>
	</body>
</html>