<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 446 2010-05-11 10:35:35Z dinhchieu $
 */
?>
<div class="t_g_box t_news_newest">
    <div class="t_g_box_head">
    	<h2><?php echo $this->translator()->widget('newest_articles'); ?></h2>
    </div>
    <div class="t_g_box_content">
    	<div id="tNewsNewestSlideshow_<?php echo $this->uuid; ?>">
		<?php if ($this->articles != null) : ?>
			<ul>
			<?php foreach ($this->articles as $index => $article) : ?>
				<li>
					<?php if ($article->image_square) : ?><a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><img src="<?php echo $article->image_square; ?>" width="60px" height="60px" /></a><?php endif; ?>
					<div>
						<strong><a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><?php echo $article->title; ?></a></strong>
						<?php echo $this->subString($article->description, 50); ?>
					</div>
				</li>
			<?php endforeach; ?>
			</ul>
		<?php endif; ?>
		</div>
	</div>			    
</div>

