<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: _footer.phtml 446 2010-05-11 10:35:35Z dinhchieu $
 */
?>
<div style="padding-top: 15px; font-size:11px; color:#444444;">
	<div class="grid_8 alpha">
		<span style="padding-left:10px;">Copyright &copy; 2010 TomatoCMS.Com. All rights reserved.</span>
	</div>
	<div class="grid_4 omega t_g_textright">
		<a href="http://www.tomatocms.com" title="Powered by TomatoCMS" target="_blank"><img src="<?php echo $this->APP_STATIC_SERVER; ?>/skins/nightspace/default/images/PoweredBy_TomatoCMS_Dark.png" border="0" width="108px" height="28px" /></a>
	</div>
</div>
<div class="clearfix"></div>
