<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 446 2010-05-11 10:35:35Z dinhchieu $
 */
?>
<div class="t_utility_social_share t_g_bottom">
	<h2>Share This Post</h2>
	<div class="t_utility_socialshare"></div>
</div>
<div class="clearfix"></div>
<script type="text/javascript">
$(document).ready(function() {
	// Get the title of page
	var title = $('head > title').html();
	// Get the current URL
	var url = window.location;
	$('.t_utility_socialshare')
		.append('<ul>'
				+'<li class="twitter"><a href="http://twitter.com/home/?status=' + title + '-' + url + '" title="<?php echo $this->translator()->widget('twitter'); ?>"></a></li>'
				+'<li class="facebook"><a href="http://www.facebook.com/share.php?u=' + url + '" title="<?php echo $this->translator()->widget('facebook'); ?>"></a></li>'
				+'<li class="technorati"><a href="http://technorati.com/faves?sub=addfavbtn&add=' + url + '" title="<?php echo $this->translator()->widget('technorati'); ?>"></a></li>'
				+'<li class="delicious"><a href="http://del.icio.us/post?url=' + url + '&title=' + title + '" title="<?php echo $this->translator()->widget('delicious'); ?>"></a></li>'
				+'<li class="stumbleupon"><a href="http://www.stumbleupon.com/submit?url=' + url + '" title="<?php echo $this->translator()->widget('stumbleupon'); ?>"></a></li>'
		+'</ul>');
});
</script>