<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />		
		<?php echo $this->headTitle('Login')?>
		<?php echo $this->headLink()->appendStylesheet("http://localhost/Apprentice_CMS/public/css/login.css") ?>
		<?php echo $this->headStyle()?>
		<?php echo $this->headScript()?>
	</head>
	<body>
		<div id="head">
		</div>
		<div id="content">
			<div class="content-left">
			</div>
			<div class="content-text">
				<div class="content-sub">
					<p id="user">
						<h6 class="username">User name:</h6>
						<input type="text" class="txtusername"/>
					</p>
				</div>
				<div class="content-sub">
					<p id="pass"> 
						<h6 class="password">Password:</h6>
						<input type="password" class="txtpassword"/>
					</p>
				</div>
				<div class="content-sub">
					<p id="forgot"><a href="">Forgot your password</a></p>
					<input type="submit" class="btn" value="Login"></input>
				</div>
				<div class="content-center">
				</div>
			</div>
			<div class="content-right">
			</div>
		</div>
		<div id="footer">
			<div id="head_footer">
				<div id="content_footer">
					<h6>Powered by Ap_CMS</h6>
				</div>
			</div>
		</div>
	</body>
</html>


