<?php echo $this->doctype(); ?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   	<?php echo $this->headLink()->appendStylesheet('/Apprentice_CMS/skin/admin/default/admin.css'); ?>
   	<?php echo $this->headLink()->appendStylesheet('/Apprentice_CMS/public/css/menu.css')?>
</head>
<body>   
	<div class="container">
	
    	<div id="header">
            <div id="h_banner">
                <div id="h_title">
                	<h1>Apprentice_CMS</h1>
                </div>
                <div id="h_infor">
                    <?php
					$auth=Zend_Auth::getInstance();
                    if(!$auth->hasIdentity()){
                    	echo "<p><a href='/Apprentice_CMS/public/admin/auth/login'>Login</a></p>";
                    }
                    else 
                    { 
                    	echo "<p>Hello,</p>".$auth->getIdentity()->user_name;
                    	echo "<a href='/Apprentice_CMS/public/admin/auth/logout'>Logout</a>";
                    }
                    ?>
                </div>
            </div>
        	<div id="h_menu">
        		<div id="menu">
        			<?php echo $this->navigation()->menu(); ?>
        		</div>
				<div>
			    <!-- <div id="menu2" style="margin-left:13%;">
   					<ul class="t_menu_menu">
   					<?php 
   						$menuBLO = new Model_MenuBLO();
   						$menus = $menuBLO->getMenus();
						$items = $menuBLO->getItems('2');
   						$menuBLO->CreateMenuMultiLevel($items)
   					?>
   					</ul>
        		</div> -->
				</div>
            </div>
            
        </div><!--header-->
        
		<div id="content">
			<?php echo $this->layout()->content?>
		</div><!--content-->  
            
        <div id="footer">
            <h4>Power By Apprentice_CMS</h4>
        </div> 
             
	</div><!--container-->
</body>
</html>