<?php echo $this->doctype(); ?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <?php echo $this->headLink()->appendStylesheet('/Apprentice_CMS/skin/admin/default/admin.css'); ?>
   <?php echo $this->headLink()->appendStylesheet('/Apprentice_CMS/public/css/Menu.css');?>   
   <?php echo $this->headScript()->appendFile('/Apprentice_CMS/js/admin/stmenu.js')
								   ->appendFile('/Apprentice_CMS/js/admin/stcode.js')
								   ->appendFile('/Apprentice_CMS/js/admin/steffie.js')
								   ->appendFile('/Apprentice_CMS/js/admin/steffslip.js')
								   ->appendFile('/Apprentice_CMS/js/admin/steffrect.js')
								   ->appendFile('/Apprentice_CMS/public/js/jquery-1.6.js')
								   ->appendFile('/Apprentice_CMS/public/js/Menu.js');?>
</head>
<body>   
	<div class="container">
	
    	<div id="header">
            <div id="h_banner">
                <div id="h_title">
                	<h1>Apprentice_CMS</h1>
                </div>
                <div id="h_infor">
                    <p>Chào, Admin. Trang Chủ Website. Đăng Xuất</p>
                </div>
            </div>
        	<div id="h_menu">
        		<div id="menu">
   					<ul class="t_menu_menu">
   					<?php 
   						$menuBLO = new Model_MenuBLO();
   						$menus = $menuBLO->getMenus();
						$items = $menuBLO->getItems('2');
   						$menuBLO->CreateMenuMultiLevel($items)
   					?>
   					</ul>
        		</div>
                

            </div>
            
        </div><!--header-->

        <div id="content">
			<?php echo $this->layout()->content?>       
        </div><!--content-->  
            
        <div id="footer">
            <h4>Power By Apprentice_CMS</h4>
        </div> 
             
	</div><!--container-->
</body>
</html>