<?php
		echo '<table align="centrer" border="1" cellspacing="2" cellpadding="2">
		<tr>
		<td align="left"><b>id</b></td>
		<td align="left"><b>name</b></td>
		<td align="left"><b>description</b></td>
		<td align="left"><b>thumbnail</b></td>
		<td align="left"><b>author</b></td>
		<td align="left"><b>email</b></td>
		<td align="left"><b>version</b></td>
		<td align="left"><b>license</b></td>
		</tr>';
		while ($row = $this->result->fetch())
		{
			echo '<tr><td align=\"left\">';
			echo $row['module_id'];
			echo '</td><td align=\"left\">';
			echo $row['name'];
			echo '</td><td align=\"left\">';
			echo $row['description'];
			echo '</td><td align=\"left\">';
			echo $row['thumbnail'];
			echo '</td><td align=\"left\">';
			echo $row['author'];
			echo '</td><td align=\"left\">';
			echo $row['email'];
			echo '</td><td align=\"left\">';
			echo $row['version'];
			echo '</td><td align=\"left\">';
			echo $row['license'];
			echo '</td></tr>';
		}
		
		echo '</table>';
