<?php
		echo '<table align="centrer" border="1" cellspacing="2" cellpadding="2">
		<tr>
		<td align="left"><b>id</b></td>
		<td align="left"><b>title</b></td>
	
		</tr>';
		/*$row = $this->result;
		
			echo '<tr><td align=\"left\">';
			echo $row['id'];
			echo '</td><td align=\"left\">';
			echo $row['title'];
			echo '</td></tr>';*/
		
		
		echo '</table>';
		
		echo "<form action='#' method='post' enctype='multipart/form-data'>";
		echo "<input type='file' name='file' />";
		echo "<input type='submit' name='btnsubmit' value='upload' />";
		echo "</form>";
