<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
</head>
<body>   
        

        <div id="content">
			<?php echo $this->layout()->content?>       
        </div><!--content-->  
            
        <div id="footer">
            <h4>Power By Apprectice_CMS</h4>
        </div> 
             
	
</body>
</html>