<?php echo $this->doctype(); ?>
<html>
<head>
	<?php echo $this->headLink()->appendStylesheet('/Apprentice_CMS/public/css/StyleSheet.css'); ?>
    <link type="text/css" rel="Stylesheet" href="StyleSheet.css" />
</head>
<body>
    <div id="main">  
    	<h4>Tạo mới bài viết</h4>      
        <div class="block">
            <h3>Title</h3>
            <div id="titles">
                <?php echo $this->newsTitle?>
            </div>
            
            <div class="control">
                <a href="#" title="Edit"><img src="/Apprentice_CMS/public/images/icon/Edit.png" /> </a>
            </div>
            <div class="clear"></div>
        </div>
        
        <div class="block">
            <h3>Description</h3>
            <div id="description">
                <?php echo $this->newsDescription?>
            </div>
            
            <div class="control">
                <a href="#" title="Edit"><img src="/Apprentice_CMS/public/images/icon/Edit.png" /> </a>
            </div>
            <div class="clear"></div>
        </div>
        
        <div class="block">
            <h3>Order news</h3>
            <div id="order">

            </div>
            
            <div class="control">
                <a href="#" title="Edit"><img src="/Apprentice_CMS/public/images/icon/Edit.png" /> </a>
            </div>
            <div class="clear"></div>
        </div>
        
        <?php 
        	$temp=new SimpleXMLElement($this->newsContent);
        	//$doc=new DOMDocument();
        	//$doc->loadHTML($this->newsContent);
        	//$dom=$doc->getElementsByTagName("div");
        	//foreach($dom as $d){
        		//echo $d->item(0)->nodevalue;
        	//}
        	foreach ($temp as $t){
        		if($t["class"]=="block")
        			echo "<div>".$t."</div>";
        	}
        ?>
        
        <div class="panel">
            <a href="#" title="New block content"><img src="/Apprentice_CMS/public/images/icon/New-document.png" /> </a>
            <a href="#" title="New image"><img src="/Apprentice_CMS/public/images/icon/New-image.png" /> </a>
            <a href="#" title="New table"><img src="/Apprentice_CMS/public/images/icon/New-table.png" /> </a>
        </div>
        
        
        <div class="block">
            <h3>Author</h3>
            <div id="author">
                <?php echo $this->newsAuthor?>
            </div>
            
            <div class="control">
                <a href="#" title="Edit"><img src="/Apprentice_CMS/public/images/icon/Edit.png" /> </a>
            </div>
            <div class="clear"></div>
        </div>
        <div class="button">
        	<a href="#" title="Save">
        		<img src="/Apprentice_CMS/public/images/icon/Save32.png" />
        	</a>
        </div>	
    </div>
</body>
</html>
