<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />	
	<?php echo $this->headTitle('View the article') ?>	
	<?php echo $this->headStyle()?>
	<?php 		
		$this->headLink()->appendStylesheet($this->url.'public/css/editor.css');
		$this->headScript()->appendFile($this->url.'public/js/editor.js'); 
		//$this->headScript()->appendFile($this->url.'public/js/jquery-ui-1.8.16.custom.min.js'); 
		//$this->headScript()->appendFile($this->url.'public/js/jquery-1.6.js'); 
		//$this->headLink()->appendStylesheet($this->url.'public/css/jquery-ui-1.8.16.custom.css');	
		  
		?>
	<!--  
	<script src="../../../../js/jquery-1.6.2.min.js"></script>
	<script src="../../../../js/jquery-ui-1.8.16.custom.min.js"></script>
	<script src="../../../../css/jquery-ui-1.8.16.custom.css"></script>
	-->


	<base href='http://jqueryui.com/' />
	<link rel="stylesheet" href="../../themes/base/jquery.ui.all.css"> 
	<script src="../../jquery-1.6.2.js"></script>
	<script src="../../ui/jquery.ui.core.js"></script>
	<script src="../../ui/jquery.ui.widget.js"></script>
	<script src="../../ui/jquery.ui.mouse.js"></script>
	<script src="../../ui/jquery.ui.draggable.js"></script>
	<script src="../../ui/jquery.ui.droppable.js"></script>
	<script src="../../ui/jquery.ui.sortable.js"></script>   
	
	<style>
	#save{
		position:absolute;
		width : 120px;
		height : 40px;
		border : none;
		border-radius:15px 15px;
		background:#F90;
		color:white;
		top : 120px;
		left: 40px;
		font-weight: 900;
	}
	</style>

	<script>
		$(document).ready(function(){
			$("#save").hide();
			$("*").css("cursor","default");
			$("#save*").css("cursor","pointer");

			//Chuột di chuyển lên span thì có hiệu ứng tí xíu:
			$("span").mouseover(function(){
				$(this).css("outline","1px dotted white");
			});

			$("span").mouseout(function(){
				$(this).css("outline","none");
			});
			//Double Click vào text để sửa nội dung nà (Cái hàm clickChangeText khai báo bên dưới):
			$("span").dblclick(clickChangeText);
		});

		//Hàm xử lý double click:
		function clickChangeText(){
			var temp=$(this);		       				
			var pretext=$(this).html();
			temp.attr("daclick","ok");
			//Tạo 1 cái div mới chứa cái editor của thằng quỷ Khoa:
            var newdiv = $("<div>");
            newdiv.attr("id","editorContainer").css("background","#888").css("border-radius","2px 2px").css("width","487");

         	//Thay thế cái thẻ đang click = cái div này:
			$(this).replaceWith(newdiv);

			//đây khởi tạo cái editor cùi pắp của thằng Khoa ở đây:
			newEditor = new Editor("newEditor","text_editorId","inputdata", "editorContainer",450,200,pretext);
            newEditor.render(); 

            //Thêm 1 cái nút Accept để click khi thay đổi xong:                                     
			btAccept = $("<input type='button' value='Accept' />");
			btAccept.css({
				"border-style":"outset",
				"border-radius":"10px 10px",
				"background":"#444",
				"color":"white",
				"margin-left":"220px"
		      });
		    btAccept.hover(function(){
				$(this).css("background","#222");
					},function(){
				$(this).css("background","#444");
				});
            newdiv.append(btAccept);

            //Sự kiện click nút Accept:
            btAccept.click(function(){
            	getData("inputdata","text_editorId");
                temp.html($("#inputdata").val());
                newdiv.replaceWith(temp);
                temp.dblclick(clickChangeText);
                $("#editorContainer").remove();
                $("#save").show();
            });     
            $("#text_editorId").focus();       
            $("#text_editorId").css("background","#777"); 
		}
	</script>
</head>
<body>
	<div id="parent">
	<hr />
	<h2><?php echo $this->title ?></h2>
	<cite><?php echo $this->author . " - " . $this->created_date ?></cite>
	<hr />
	<span class="description" >
		<?php echo $this->description ?>
	</span>
	<hr />
	<span class="content">
		<?php echo $this->content ?>
	</span>
	</div>
	<hr />
	<?php
		echo "<h2>Title</h2><br />";	
	
		$has_comment = false;
		while ($row = $this->comments->fetch()) {
			if ($row['is_active'] == 1) {
				$has_comment = true;
				echo "<strong>" . $row['title'] . "</strong>";
				echo "<cite> at " . $row['created_date'] . "</cite><br />";
				echo $row['content'] . "<br /><br />";
			}
		}
		if ($has_comment == false) {
			echo "There are no comments available.";
		} 
	?>
	<hr />
	<?php
		if ($this->allowComment == 1) {
			$article_id = $this->id;
			echo "<h2>Write your comment</h2><br />";
			echo "
				<form action='/Apprentice_CMS/public/comment/admin/add' method='post' name='sendCommentForm' id='sendCommentForm' enctype='multipart/form-data'>
				<div>
					<label>Full name: </label>
					<input type='text' name='name_comment' id='name_comment' style='width: 250px;' />
				</div>
				<br />
				<div>
					<label>Email: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
					<input type='text' name='email_comment' id='email_comment' style='width: 250px;' />
				</div>
				<br />
				<div>
					<label>Title: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
					<input type='text' name='title_comment' id='title_comment' style='width: 250px;' />
				</div>
				<br />
				<label>Content:</label>
				<br />
				<textarea name='content_comment' cols='30' rows='10'></textarea>
				<br />
				<input type='submit' name='send' value='Send' />
				<input type='hidden' name='article_id' id='article_id' value='$article_id' />
				</form>";
		}
	?>
	<form id="frm" method="post" >
		<input type="submit" id="save" name="save" value="Click để save nà" onclick="saveClick();">
	</form>
	<script>
	//Do cách kia phá sản nên đây là 1 cách cực kỳ cùi chuối, sự dụng tạm thời:
	//Dùng hơi bị nhiều mảng để lưu các cái thứ cần thiết khi duyệt qua all các thẻ span của trang web:
	var content = new Array();
	var attrName = new Array();
	var hdAttrName = new Array();
	var hdNewContent = new Array();
	function saveClick(){
		$("#parent span").each(function(i){
		    numElement = i;
			hdContentName = "newContent"+i;
			hhdAttrName = "attrName"+i;
			content[i] = $(this).html();
			attrName[i] = $(this).attr("class");
			hdAttrName[i] = $("<input type='hidden' name='"+hhdAttrName+"'  value='"+attrName[i]+"'/>");
			hdNewContent[i] = $("<input type='hidden' name='"+hdContentName+"' value='"+content[i]+"'/>");
			$("#frm").append(hdAttrName[i]);
			$("#frm").append(hdNewContent[i]);
		});
		var hdNumElement = $("<input type='hidden' name='numElement'  value='"+numElement+"'/>"); 
	    $("#frm").append(hdNumElement);   
	}
	</script>
</body>
</html>