
<html>
	<head>
		<style type="text/css">
			{margin:0; padding:0}
.container{
	width:960px;
	margin:20px auto;
	border:blue 5px solid;
}
.mainContent{
	height:100px;
	border:red 1px solid;
}
.viewDetail{
	border:yellow 3px solid;
	height:500px;
}
		</style>
	</head>
	<body>
	<div class="container">
		<div class="header">
			<h1>Template</h1>
		</div>
		<div class="mainContent">
			<p>template 1</p>
			<a href="<?php echo "http://localhost/Apprentice_CMS/public/admin/login"?>" >New template</a>
		</div>
		<div class="viewdetail">
			<html>
				<head>
				</head>
				<body>
					<?php echo "day la content";?> 
					<?echo $this->template['mail']?>
				</body>
			</html>		
		</div>
	</div>
		
	</body>
</html>
