<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	</head>
	<body>
		<div id="container">
			<div id="title">
				<h1>Template</h1>
				<p>Dưới đây là danh sách các template. Bạn có thể chọn template và skin cho trang web.</p>
			</div>
			<div class="content">
				<?php foreach ($this->templates as $template){?>
					<div class="template">
						<div class="template_name">
							<h2><?php echo $template['name'];?></h2>
						</div>
						
						<div id="template_infor">
							<?php echo "Tác Giả: " . $template['author']; ?><br />
							<?php echo "Phiên Bản: " . $template['version']; ?>
						</div>
						
						<div id="template_img">
							<img src="images/paper.jpg">Hình ảnh Template: <?php echo $template['name'];?></img>
						</div>
						
						<div class="template_action">
							<?php //echo $template['name'];?>
							<form action="#" method="post" enctype='multipart/form-data'>					
								<input type="submit" value="<?php echo $template['name'];?>" name="btnChon" id="btnChon"/>	
							</form>
						</div>
						
					</div>
					
				<?php }?>	
			</div>
			
		</div>
		
		
	</body>
</html>


