<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Privilege</title>

<style type="text/css">
#controller{
	font-size:17px;
	font-weight:bold;
	color:yellow;
	text-align: left;
	margin-left: 40px;
	cursor: default;
}

#leftFrame{
	float:left;
	margin-left: 40px;
	height: 295px;
	width: 130px;
}

#rightFrame{
	float:left;
	margin-left: 37px;
	height: 360px;
	width: 400px;
	background:#320;
	border-style: inset;
	border-color: grey;
	overflow: auto;
	border-right-style:none;	
}
		
a{
	text-decoration: none;
	cursor:default;
	color: Orange;
}

#main{
	background-color: #333;
}

#privilegeItem{
	color:silver;
	font-weight: bold;
	cursor: default;	
}

#privilegeItem:hover{
	background: #333;
}

#privilegeList{
	height: 272px;
	overflow: auto;
}

	
#ModuleItem{
	font-size: 17px;	
	color: white;
	height: 28px;
	background: #300;
	border-style: inset;
	border-color: grey; 
	border-right-style:none;
}
	
#ModuleItem:hover{
	background-color: gray;
}
	
.module{
	cursor:default;
	text-align: center;	
}

a.bt:hover {
	color: Red;
}
a.bt{
	float:right;
	margin-right: 60px;
	text-align: right;
}

#description{
	margin-left: 130px;
	text-align: left;
}

.btSubmit{
	text-align: center;
	border: none;
	background:#F90;
	color:#FFF;
	width:80px;
	height:30px;
	border:none;
	border-radius:8px 8px;
	font-weight:900;
	margin-left:40px;
	cursor: pointer;
}

h1{
	font-size:40px;
	color: white;
	text-align: center;
	cursor: default;
}

</style>

<script language="javascript">
	function changeUrl(name)
	{
		window.location.href = "../privilege/list?modulename="+name;
	}
	function privilegeChangeUrl(actName,action,id,name){
		window.location.href = "../privilege/"+actName+"?action="+action+"&id="+id+"&module="+name;
	}
	</script>
</head>	
<body>
<h1>Privileges</h1>
<div id="leftFrame">
<?php		
	//hien thi danh sach cac module (danh sach nay co the click duoc):
	if($this->moduleResult){
		while ($rows = $this->moduleResult->fetch()){			
			$moduleName = $rows['module_name'];
			echo "<div id='ModuleItem' onclick='changeUrl(\"".$moduleName."\")'>";					
			echo "<div class='module'>$moduleName</div>";
			echo "</div>";	
		}
	}
?>
</div>
<div id='rightFrame'>
<?php
	$controllerArray = $this->conArray;
	$num = count($controllerArray);
	//Hien thi danh sach cac quyen + cac button Add va Delete tuong ung dzoi module da click:	
	if($this->priResult){
		while($rows = $this->priResult->fetch()){
			$isDeleted = $rows['isDeleted'];
			if($isDeleted == 0){
				$btnName = "[ Delete ]";
				$action = "delete";
			}
			else{
				$btnName = "[ &nbsp Add &nbsp ]";
				$action = "add";
			}
			$id = (string)$rows['privilege_id'];	
			$module = (string)$rows['module_name'];
			$description = 	$rows['description'];
			$controller = $rows['controller_name'];
			
			for($i=0;$i<$num;$i++){
				if($controller == $controllerArray[$i]){
					$controllerArray[$i] = null;
					if($controllerArray[0]==null && $num>1){;
						echo "<br>";
					}
					echo "<div id='controller'>+Manage $controller:</div>";	
				}						
			}
			
			echo "<div id='privilegeItem' onclick='privilegeChangeUrl(\"".$action."\",\"".$action."\",\"".$id."\",\"".$module."\")'><div id='description'><li>$description";
			echo "<a class='bt'>$btnName</a></li></div></div>";			
		}
	}
?>
</div>
<br>
<form name ="frm" method="post">
<input type="submit" name="back" class="btSubmit" value="Back"></input>
</form>
</body>
</html>