<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Privilege</title>

<style type="text/css">
a.bt:link,a.bt:visited {
	text-decoration: none;
	color: Orange;
}

#main{
	background-color: black;
}

a#back{
	font-size:17px;
	text-decoration: none;
	color: silver;
	border-style: outset;
	border-color: silver;	
	margin-left: 350px;	

}
a#back:HOVER{
	color: orange;
	border-color: orange;	
}
#description{
	color:silver;
	font-weight: bold;
}

#description:hover{
	background: #333;
}

#modulelist {
	float: left;
	height: 295px;
	width: 130px;
	text-align: center;
	border-color: silver;
	border-style: inset;
	background-color:black;
	margin-left: 130px;
}

#PrivilegeList {	
	text-align: center;
	height: 295px;
	width: 500px;
	border-style: inset;
	background-color:black;
	border-color: silver;
	margin-left: 130px;
}

#Detail{
	height: 272px;
	overflow: auto;
}

#ModuleItem:Hover{
	background-color: #333;
}

a.module:link,a.module:visited {
	text-decoration: none;
	font-size: 18px;
	color: white;
}

a.bt:hover {
	text-decoration: underline;
}

a.module:hover {
	font-weight: bolder;
	text-decoration: underline;
}
h3{
	font-size:18px;
	color:  appworkspace;
	background-color: black;
}
h1{
	font-size:40px;
	color: while;
	text-align: center;
}
</style>

<script language="javascript">
	function changeUrl(name)
	{
		window.location.href = '../privilege/list?modulename='+name;
	}
	</script>
</head>	
<body bgcolor="black">
<h1>Privileges</h1>
<div class="List">
<div id='modulelist'>
<h3><strong>Module List</strong></h3><hr>
<?php		
	//hien thi danh sach cac module (danh sach nay co the click duoc):
	if($this->moduleResult){
		while ($moduleRows = $this->moduleResult->fetch()){			
			$moduleName = $moduleRows['module_name'];
			echo "<div id='ModuleItem'>";					
			echo "<a href= '../privilege/list?modulename=$moduleName' class='module'>$moduleName</a>";
			echo "<hr>";
			echo "</div>";	
		}
	}
?>
</div>
<div id='PrivilegeList'>
<h3><strong>Privilige List</strong></h3><hr>
<div id='Detail'>
<?php
	//Hien thi danh sach cac quyen + cac button Add va Delete tuong ung dzoi module da click:
	if($this->desResult){
		while($desRows = $this->desResult->fetch()){
			//echo "<hr>";
			$isDeleted = $desRows['isDeleted'];
			if($isDeleted == 0){
				$btnName = "[ Delete ]";
				$action = "delete";
			}
			else{
				$btnName = "[ Add ]";
				$action = "add";
			}
			$id = (string)$desRows['privilege_id'];	
			$module = (string)$desRows['module_name'];
			$description = 	$desRows['description'];	
			echo "<div id='description'>$description<br>";
			echo "<a href='../privilege/$action?action=$action&id=$id&module=$module' class='bt'>$btnName</a></div>";
			echo "<hr>";
		}
	}
?>
</div>
</div>
</div>
<br>
<a href ="../" id='back'">Back</a>
</body>
</html>